services:
  hemi-network:
    container_name: hemi-network
    image: ghcr.io/zuperhunt/hemi-network:v0.4.5-zh-2
    restart: unless-stopped
    volumes:
      - ./workdir:/app/secrets
    env_file:
      ./.env
